---
- name: push spark suffle jar to nodes
  tags: configure_spark
  copy:
    src: "/tmp/spark-{{ spark_ver }}-yarn-shuffle.jar"
    dest: "{{ hadoop_home }}/share/hadoop/yarn/lib/"
    force: true
    owner: "hadoop"
    group: "hadoop"
    mode: "0770"

